### ISSUE TITLE
Pogreska kod prijave

### ISSUE THREAD

**Issue by HSanel2000** [vdavid033/iooa-2024-aukcije-1#41]
Greska:
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by dniksic** [comment]
Greška je riješena, sada prijava uspješno prolazi ukoliko je korisnik u bazi! Problem je bio u komunikaciji između FE/BE.

![image](https://github.com/vdavid033/iooa-2024-aukcije-1/assets/162477381/b7eb16db-f19e-41da-9641-0a72ac0108ba)
