### ISSUE TITLE
Odluka o mogućnostima registriranih, prijavljenih i gost korisnika

### ISSUE THREAD

**Issue by dniksic** [vdavid033/iooa-2024-aukcije-1#42]
Prijedlog je da sustav zatvorimo da se ne može koristiti bez prijave korisnika. odnosno za početak korisnik nam se treba prijaviti, ako nema račun registrirati se, potom se prijaviti i koristiti stranicu.

**Comment by HSanel2000** [comment]
Slazem se ovo bi trebali implementirati
