### ISSUE TITLE
Prijava i odjava

### ISSUE THREAD

**Issue by HSanel2000** [vdavid033/iooa-2024-aukcije-1#43]
Prijava radi, ali iz nekog razloga se ona ne evidentira na stranici te je trenutno ne moguce implementirati logiku za odjavu

**Comment by dniksic** [comment]
Implementirano, ugrađena autentikacija i token. dalje treba vidjeti što će raditi prijavljeni korisnik i što ćemo skriti od nekog neprijavljenog. 

![Image](https://github.com/vdavid033/iooa-2024-aukcije-1/assets/162477381/43827ff4-a1fa-4a4d-94ce-cd05118f9328)
