### ISSUE TITLE
Proširujući izbornik prijedlog za prebacivanje na gornju traku. 

### ISSUE THREAD

**Issue by dniksic** [vdavid033/iooa-2024-aukcije-1#47]
Potrebno urediti prikaz izbornika, ne radi baš automatsko zatvaranje, prikaz preko Page djela treba riješiti. Možda ga i ukloniti po meni i tih par opcija prebaciti u gornju traku na main layoutu i gotovo.  Nema smisla imati duple opcije u 2 izbornika jer je Prijava/Registracija sadržana u top djelu navigacije i također u izborniku. Možda bi tako stranica bila puno preglednija. Ako je moguć dogovor. Dakle predložio bi slijedeće:

![image](https://github.com/vdavid033/iooa-2024-aukcije-1/assets/162477381/8a55cc32-1a06-430f-927a-4c1d9543e4fc)

**Comment by HSanel2000** [comment]
Popravljen i uredjen izbornik, ostalo je na otvaranje, prijava i registracija nalaze se i na desnoj strani i u draweru ukoliko korisnik nije prijavljen
