### ISSUE TITLE
Trenutna cijena aukcije se ne mijenja nakon unosa ponude

### ISSUE THREAD

**Issue by ivan-turk** [vdavid033/iooa-2024-aukcije-1#55]
Kada korisnik unese ponudu na aukciju, trenutna cijena aukcije se ne ažurira kako bi održavala novu unešenu ponudu

**Comment by dniksic** [comment]
Problem je riješen, dodana je mogućnost unosa ponude odnosno time i promjene trenutne cijene za pojedinu važeću aukciju. Riješene restrikcije unosa, dobivanje ID kroz AWT token. 
![1](https://github.com/vdavid033/iooa-2024-aukcije-1/assets/162477381/1ff9756a-5994-43f7-b753-905be017649c)
![2](https://github.com/vdavid033/iooa-2024-aukcije-1/assets/162477381/37e4a73e-2cf6-4266-ac50-c1e607365135)
![3](https://github.com/vdavid033/iooa-2024-aukcije-1/assets/162477381/b280bda6-f9ed-42d1-b03a-2c4bec2d3755)
![4](https://github.com/vdavid033/iooa-2024-aukcije-1/assets/162477381/57fe1eeb-40cc-49a8-8828-5933c1c4aab4)
![5](https://github.com/vdavid033/iooa-2024-aukcije-1/assets/162477381/b80bf34f-78b8-499a-8b6b-f1d0868a4428)
